version: '3.8'

services:
  db:
    image: postgres:13-alpine
    container_name: myapp_postgres
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"